### ISSUE TITLE
This is what chroot output.

### ISSUE THREAD

**Issue by 62f** [ProjectZeroDays/iSH-Auto-Config#1]
iPhone:/alpine/root# . setup-x11vnc-server.sh
Connectsh: setup-x11vnc-server.sh: x11vnc: not found
iPhone:/alpine/root# cat: can't open '/dev/location': No such file or directory
iPhone:/alpine/root# ./setup-x11vnc-server.sh
Connect[2]+  Done(127)                  x11vnc -create -noshm -forever && x11vnc -rfbauth -usepw -ssl -stunnel "~/.vnc/passwd"
[1]+  Done(1)                    cat /dev/location 1>/dev/null
./setup-x11vnc-server.sh: line 25: iPhone:/alpine/root# x11vnc: not found
cat: can't open '/dev/location': No such file or directory
iPhone:/alpine/root# . ./setup-x11vnc-server.sh
Connectsh: ./setup-x11vnc-server.sh: x11vnc: not found
iPhone:/alpine/root# cat: can't open '/dev/location': No such file or directory
 
[2]+  Done(127)                  x11vnc -create -noshm -forever && x11vnc -rfbauth -usepw -ssl -stunnel "~/.vnc/passwd"
[1]+  Done(1)                    cat /dev/location 1>/dev/null

**Comment by 62f** [comment]
ln -s /dev $(dirname $0)/dev

cat $(dirname $0)/dev/location > $(dirname $0)/dev/null & #!

**Comment by ProjectZeroDays** [comment]
I noticed the problem finding .sh files was due to chmod not properly being implemented early on in the first and second script. Ive fixed that... going to organize all this, rewrite it and push tomorrow morning when i finish and then maybe play with Ub2
